---
title: エラーの終了 |Microsoft Docs
ms.custom: ''
ms.date: 09/13/2016
ms.reviewer: ''
ms.suite: ''
ms.tgt_pltfrm: ''
ms.topic: article
ms.assetid: b804e738-aefa-41bb-9649-f9ed897fd96c
caps.latest.revision: 8
ms.openlocfilehash: d1967fe7996f75ec5229920f7ec49aa5ff6bdbfd
ms.sourcegitcommit: caac7d098a448232304c9d6728e7340ec7517a71
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/16/2019
ms.locfileid: "58059237"
---
# <a name="terminating-errors"></a><span data-ttu-id="6934e-102">終了するエラー</span><span class="sxs-lookup"><span data-stu-id="6934e-102">Terminating Errors</span></span>

<span data-ttu-id="6934e-103">このトピックでは、エラーの終了レポートに使用する方法について説明します。</span><span class="sxs-lookup"><span data-stu-id="6934e-103">This topic discusses the method used to report terminating errors.</span></span> <span data-ttu-id="6934e-104">コマンドレットは、内からメソッドを呼び出す方法についても説明し、メソッドが呼び出されたときに、Windows PowerShell ランタイムによって返される例外について説明します。</span><span class="sxs-lookup"><span data-stu-id="6934e-104">It also discusses how to call the method from within the cmdlet, and it discusses the exceptions that can be returned by the Windows PowerShell runtime when the method is called.</span></span>

<span data-ttu-id="6934e-105">終了中にエラーが発生した、コマンドレットは呼び出すことによって、エラーを報告する必要があります、 [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError)メソッド。</span><span class="sxs-lookup"><span data-stu-id="6934e-105">When a terminating error occurs, the cmdlet should report the error by calling the [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) method.</span></span> <span data-ttu-id="6934e-106">このメソッドは、終了エラーの原因となった状態を説明するエラー レコードを送信するためのコマンドレットを使用します。</span><span class="sxs-lookup"><span data-stu-id="6934e-106">This method allows the cmdlet to send an error record that describes the condition that caused the terminating error.</span></span> <span data-ttu-id="6934e-107">エラー レコードの詳細については、[Windows PowerShell のエラー レコード](./windows-powershell-error-records.md)を参照してください。</span><span class="sxs-lookup"><span data-stu-id="6934e-107">For more information about error records, see [Windows PowerShell Error Records](./windows-powershell-error-records.md).</span></span>

<span data-ttu-id="6934e-108">ときに、 [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError)メソッドが呼び出されると、Windows PowerShell ランタイムは完全に、パイプラインの実行を停止し、スロー、 [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException)例外。</span><span class="sxs-lookup"><span data-stu-id="6934e-108">When the [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) method is called, the  Windows PowerShell runtime permanently stops the execution of the pipeline and throws a [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) exception.</span></span> <span data-ttu-id="6934e-109">呼び出すしようとした後続[System.Management.Automation.Cmdlet.WriteObject](/dotnet/api/System.Management.Automation.Cmdlet.WriteObject)、 [System.Management.Automation.Cmdlet.WriteError](/dotnet/api/System.Management.Automation.Cmdlet.WriteError)、またはその他のいくつかの Api により、をスローするこれらの呼び出し[System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException)例外。</span><span class="sxs-lookup"><span data-stu-id="6934e-109">Any subsequent attempts to call [System.Management.Automation.Cmdlet.WriteObject](/dotnet/api/System.Management.Automation.Cmdlet.WriteObject), [System.Management.Automation.Cmdlet.WriteError](/dotnet/api/System.Management.Automation.Cmdlet.WriteError), or several other APIs causes those calls to throw a [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) exception.</span></span>

<span data-ttu-id="6934e-110">[System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException)例外は、場合は、ユーザーが、パイプラインを停止するように求められます、パイプライン内の別のコマンドレットは、終了エラーを報告する場合、またはパイプラインが停止した場合にも発生することができます何らかの理由で完了前にします。</span><span class="sxs-lookup"><span data-stu-id="6934e-110">The [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) exception can also occur if another cmdlet in the pipeline reports a terminating error, if the user has asked to stop the pipeline, or if the pipeline has been halted before completion for any reason.</span></span> <span data-ttu-id="6934e-111">コマンドレットは、キャッチする必要はありません、 [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException)例外しない限り、リソースまたは内部の状態、クリーンアップを開く必要があります。</span><span class="sxs-lookup"><span data-stu-id="6934e-111">The cmdlet does not need to catch the [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) exception unless it must clean up open resources or its internal state.</span></span>

<span data-ttu-id="6934e-112">コマンドレットは、終了エラーを報告する前に、任意の数の出力オブジェクトまたは未終了エラーを記述できます。</span><span class="sxs-lookup"><span data-stu-id="6934e-112">Cmdlets can write any number of output objects or non-terminating errors before reporting a terminating error.</span></span> <span data-ttu-id="6934e-113">ただし、終了エラーは、パイプラインと、エラーを終了しながら、さらに出力なしに完全に停止または未終了エラーを報告することができます。</span><span class="sxs-lookup"><span data-stu-id="6934e-113">However, the terminating error permanently stops the pipeline, and no further output, terminating errors, or non-terminating errors can be reported.</span></span>

<span data-ttu-id="6934e-114">コマンドレットを呼び出すことができます[System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError)を呼び出したスレッドからのみ、 [System.Management.Automation.Cmdlet.BeginProcessing](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing)、 [System.Management.Automation.Cmdlet.ProcessRecord](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord)、または[System.Management.Automation.Cmdlet.EndProcessing](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing)処理方法を入力します。</span><span class="sxs-lookup"><span data-stu-id="6934e-114">Cmdlets can call [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) only from the thread that called the [System.Management.Automation.Cmdlet.BeginProcessing](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing), [System.Management.Automation.Cmdlet.ProcessRecord](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord), or [System.Management.Automation.Cmdlet.EndProcessing](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing) input processing method.</span></span> <span data-ttu-id="6934e-115">呼び出すしないで[System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError)または[System.Management.Automation.Cmdlet.WriteError](/dotnet/api/System.Management.Automation.Cmdlet.WriteError)別のスレッドから。</span><span class="sxs-lookup"><span data-stu-id="6934e-115">Do not attempt to call [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) or [System.Management.Automation.Cmdlet.WriteError](/dotnet/api/System.Management.Automation.Cmdlet.WriteError) from another thread.</span></span> <span data-ttu-id="6934e-116">代わりに、エラーは、メイン スレッドに伝達する必要があります。</span><span class="sxs-lookup"><span data-stu-id="6934e-116">Instead, errors must be communicated back to the main thread.</span></span>

<span data-ttu-id="6934e-117">実装で例外をスローすることができます、コマンドレット、 [System.Management.Automation.Cmdlet.BeginProcessing](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing)、 [System.Management.Automation.Cmdlet.ProcessRecord](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord)、または[System.Management.Automation.Cmdlet.EndProcessing](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing)メソッド。</span><span class="sxs-lookup"><span data-stu-id="6934e-117">It is possible for a cmdlet to throw an exception in its implementation of the [System.Management.Automation.Cmdlet.BeginProcessing](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing), [System.Management.Automation.Cmdlet.ProcessRecord](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord), or [System.Management.Automation.Cmdlet.EndProcessing](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing) method.</span></span> <span data-ttu-id="6934e-118">(Windows PowerShell ホストを停止するいくつかの重大なエラー条件) を除くこれらのメソッドからスローされた例外は、パイプラインが全体として Windows PowerShell ではなくを停止する終了エラーとして解釈されます。</span><span class="sxs-lookup"><span data-stu-id="6934e-118">Any exception thrown from these methods (except for a few severe error conditions that stop the Windows PowerShell host) is interpreted as a terminating error which stops the pipeline, but not Windows PowerShell as a whole.</span></span> <span data-ttu-id="6934e-119">(これは、コマンドレットのメイン スレッドにのみ適用されます。</span><span class="sxs-lookup"><span data-stu-id="6934e-119">(This applies only to the main cmdlet thread.</span></span> <span data-ttu-id="6934e-120">キャッチされない例外、コマンドレットによって生成されたスレッドで一般に、停止、Windows PowerShell ホストします。)使用することをお勧めします[System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError)エラー レコードがエラー状態に関する追加情報を提供するために例外がスローされるのではなくするのに便利です。エンドユーザー。</span><span class="sxs-lookup"><span data-stu-id="6934e-120">Uncaught exceptions in threads spawned by the cmdlet, in general, halt the Windows PowerShell host.) We recommend that you use [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) rather than throwing an exception because the error record provides additional information about the error condition, which is useful to the end-user.</span></span> <span data-ttu-id="6934e-121">コマンドレットをキャッチして、すべての例外の処理に対してマネージ コードのガイドラインを受け入れる必要がある (`catch (Exception e)`)。</span><span class="sxs-lookup"><span data-stu-id="6934e-121">Cmdlets should honor the managed code guideline against catching and handling all exceptions (`catch (Exception e)`).</span></span> <span data-ttu-id="6934e-122">エラー レコードには、既知および必要な型の例外のみを変換します。</span><span class="sxs-lookup"><span data-stu-id="6934e-122">Convert only exceptions of known and expected types into error records.</span></span>

## <a name="see-also"></a><span data-ttu-id="6934e-123">参照</span><span class="sxs-lookup"><span data-stu-id="6934e-123">See Also</span></span>

[<span data-ttu-id="6934e-124">System.Management.Automation.Cmdlet.BeginProcessing</span><span class="sxs-lookup"><span data-stu-id="6934e-124">System.Management.Automation.Cmdlet.BeginProcessing</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing)

[<span data-ttu-id="6934e-125">System.Management.Automation.Cmdlet.EndProcessing</span><span class="sxs-lookup"><span data-stu-id="6934e-125">System.Management.Automation.Cmdlet.EndProcessing</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing)

[<span data-ttu-id="6934e-126">System.Management.Automation.Cmdlet.ProcessRecord</span><span class="sxs-lookup"><span data-stu-id="6934e-126">System.Management.Automation.Cmdlet.ProcessRecord</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord)

[<span data-ttu-id="6934e-127">System.Management.Automation.Pipelinestoppedexception</span><span class="sxs-lookup"><span data-stu-id="6934e-127">System.Management.Automation.Pipelinestoppedexception</span></span>](/dotnet/api/System.Management.Automation.PipelineStoppedException)

[<span data-ttu-id="6934e-128">System.Management.Automation.Cmdlet.Throwterminatingerror\*</span><span class="sxs-lookup"><span data-stu-id="6934e-128">System.Management.Automation.Cmdlet.Throwterminatingerror\*</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError)

[<span data-ttu-id="6934e-129">System.Management.Automation.Cmdlet.WriteError</span><span class="sxs-lookup"><span data-stu-id="6934e-129">System.Management.Automation.Cmdlet.WriteError</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.WriteError)

[<span data-ttu-id="6934e-130">Windows PowerShell のエラー レコード</span><span class="sxs-lookup"><span data-stu-id="6934e-130">Windows PowerShell Error Records</span></span>](./windows-powershell-error-records.md)

[<span data-ttu-id="6934e-131">Windows PowerShell コマンドレットの記述</span><span class="sxs-lookup"><span data-stu-id="6934e-131">Writing a Windows PowerShell Cmdlet</span></span>](./writing-a-windows-powershell-cmdlet.md)
